import { useState, useMemo } from 'react';
import { SYSTEMS, SYSTEM_CATEGORIES, CONDITIONS, CONDITION_LABEL, suggestQuantity } from '../lib/systems';
import { summarizeCapex, formatCurrency, URGENCY_LABEL, currentYear } from '../lib/capex';

const inputBase = {
  padding: '8px 10px', fontSize: 14, borderRadius: 6,
  background: 'rgba(255,255,255,0.06)', border: '1px solid rgba(255,255,255,0.12)',
  color: '#eee', fontFamily: "'DM Sans', sans-serif", outline: 'none',
  boxSizing: 'border-box', width: '100%',
};

const URGENCY_COLORS = {
  immediate: '#e94560',
  '1-3': '#f0a500',
  '4-7': '#3b82f6',
  '8+': '#48c78e',
};

function initRows(property) {
  return SYSTEMS.map(s => ({
    system_key: s.key,
    included: false,
    year_installed: '',
    condition: 'good',
    quantity: suggestQuantity(s, property),
  }));
}

export default function CapExCalculator() {
  const [property, setProperty] = useState({ square_footage: '', unit_count: '1', year_built: '' });
  const [rows, setRows] = useState(() => initRows(property));
  const [expandedCat, setExpandedCat] = useState(null);
  const [copied, setCopied] = useState(false);

  const updateProperty = (key, val) => {
    const cleaned = val.replace(/[^0-9]/g, '');
    const next = { ...property, [key]: cleaned };
    setProperty(next);
    if (key === 'square_footage' || key === 'unit_count') {
      setRows(prev => prev.map(r => {
        if (r.included) return r;
        const sys = SYSTEMS.find(s => s.key === r.system_key);
        return { ...r, quantity: suggestQuantity(sys, next) };
      }));
    }
  };

  const toggleSystem = (key) => {
    setRows(prev => prev.map(r => {
      if (r.system_key !== key) return r;
      const next = { ...r, included: !r.included };
      if (next.included && !r.year_installed && property.year_built) {
        next.year_installed = property.year_built;
      }
      if (next.included) {
        const sys = SYSTEMS.find(s => s.key === key);
        next.quantity = suggestQuantity(sys, property);
      }
      return next;
    }));
  };

  const updateRow = (key, field, val) => {
    setRows(prev => prev.map(r => {
      if (r.system_key !== key) return r;
      if (field === 'year_installed' || field === 'quantity') {
        return { ...r, [field]: val.replace(/[^0-9]/g, '') };
      }
      return { ...r, [field]: val };
    }));
  };

  const includeAll = () => {
    setRows(prev => prev.map(r => {
      if (r.included) return r;
      const sys = SYSTEMS.find(s => s.key === r.system_key);
      return {
        ...r,
        included: true,
        year_installed: r.year_installed || property.year_built || '',
        quantity: suggestQuantity(sys, property),
      };
    }));
    setExpandedCat(SYSTEM_CATEGORIES[0]);
  };

  const summary = useMemo(() => summarizeCapex(rows), [rows]);
  const includedCount = rows.filter(r => r.included).length;
  const yr = currentYear();

  const copyResults = () => {
    if (summary.includedCount === 0) return;
    const lines = [
      'CapEx Projection Summary',
      '========================',
      `Property: ${property.square_footage ? property.square_footage + ' sq ft' : 'N/A'} | ${property.unit_count || 1} unit(s) | Built ${property.year_built || 'N/A'}`,
      '',
      `Total CapEx: ${formatCurrency(summary.total)}`,
      `  Immediate: ${formatCurrency(summary.byUrgency.immediate)}`,
      `  1-3 Years: ${formatCurrency(summary.byUrgency['1-3'])}`,
      `  4-7 Years: ${formatCurrency(summary.byUrgency['4-7'])}`,
      `  8+ Years:  ${formatCurrency(summary.byUrgency['8+'])}`,
      '',
      'Systems Breakdown:',
      ...summary.systems.map(s =>
        `  ${s.name}: ${formatCurrency(s.replacementCost)} | ${s.remainingLife != null ? s.remainingLife + ' yrs remaining' : 'No year set'} | ${s.urgency ? URGENCY_LABEL[s.urgency] : ''}`
      ),
      '',
      'Generated by UC30 Free Tools — uc30.com/tools/capex-calculator',
    ];
    navigator.clipboard.writeText(lines.join('\n')).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  };

  return (
    <div>
      {/* Property Basics */}
      <div style={{
        fontSize: 11, fontWeight: 700, color: '#e94560', letterSpacing: 1,
        marginBottom: 10,
      }}>
        PROPERTY DETAILS
      </div>
      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: 8, marginBottom: 20 }}>
        {[
          { key: 'square_footage', label: 'Square Feet', placeholder: '1,500' },
          { key: 'unit_count', label: 'Units', placeholder: '1' },
          { key: 'year_built', label: 'Year Built', placeholder: '1995' },
        ].map(f => (
          <div key={f.key}>
            <label style={{ fontSize: 11, color: '#888', fontWeight: 500, display: 'block', marginBottom: 4 }}>
              {f.label}
            </label>
            <input
              type="text"
              inputMode="numeric"
              value={property[f.key]}
              onChange={e => updateProperty(f.key, e.target.value)}
              placeholder={f.placeholder}
              style={inputBase}
            />
          </div>
        ))}
      </div>

      {/* Summary Cards */}
      {includedCount > 0 && (
        <div style={{ marginBottom: 20 }}>
          <div style={{
            display: 'flex', gap: 8, marginBottom: 12,
          }}>
            <div style={{
              flex: 1, textAlign: 'center', padding: '14px 6px', borderRadius: 10,
              background: 'rgba(255,255,255,0.02)', border: '1px solid rgba(255,255,255,0.06)',
            }}>
              <div style={{ fontSize: 20, fontWeight: 700, color: '#eee' }}>
                {formatCurrency(summary.total, { compact: summary.total > 99999 })}
              </div>
              <div style={{ fontSize: 10, color: '#666', marginTop: 4, letterSpacing: 0.5 }}>
                TOTAL CAPEX
              </div>
            </div>
            <div style={{
              flex: 1, textAlign: 'center', padding: '14px 6px', borderRadius: 10,
              background: summary.byUrgency.immediate > 0 ? 'rgba(233,69,96,0.06)' : 'rgba(255,255,255,0.02)',
              border: `1px solid ${summary.byUrgency.immediate > 0 ? 'rgba(233,69,96,0.15)' : 'rgba(255,255,255,0.06)'}`,
            }}>
              <div style={{ fontSize: 20, fontWeight: 700, color: summary.byUrgency.immediate > 0 ? '#e94560' : '#666' }}>
                {formatCurrency(summary.byUrgency.immediate, { compact: true })}
              </div>
              <div style={{ fontSize: 10, color: '#666', marginTop: 4, letterSpacing: 0.5 }}>
                IMMEDIATE
              </div>
            </div>
          </div>

          {/* Urgency breakdown bar */}
          {summary.total > 0 && (
            <div style={{
              display: 'flex', borderRadius: 6, overflow: 'hidden', height: 8, marginBottom: 8,
              background: 'rgba(255,255,255,0.04)',
            }}>
              {['immediate', '1-3', '4-7', '8+'].map(bucket => {
                const pct = summary.total > 0 ? (summary.byUrgency[bucket] / summary.total) * 100 : 0;
                if (pct === 0) return null;
                return (
                  <div key={bucket} style={{
                    width: `${pct}%`, background: URGENCY_COLORS[bucket],
                    minWidth: pct > 0 ? 4 : 0,
                  }} />
                );
              })}
            </div>
          )}
          <div style={{ display: 'flex', gap: 12, justifyContent: 'center', flexWrap: 'wrap' }}>
            {['immediate', '1-3', '4-7', '8+'].map(bucket => (
              <div key={bucket} style={{ display: 'flex', alignItems: 'center', gap: 4 }}>
                <div style={{ width: 8, height: 8, borderRadius: 2, background: URGENCY_COLORS[bucket] }} />
                <span style={{ fontSize: 10, color: '#888' }}>
                  {URGENCY_LABEL[bucket]}: {formatCurrency(summary.byUrgency[bucket], { compact: true })}
                </span>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Include All / Copy buttons */}
      <div style={{ display: 'flex', gap: 8, marginBottom: 16 }}>
        {includedCount < SYSTEMS.length && (
          <button
            onClick={includeAll}
            style={{
              flex: 1, padding: '8px 12px', fontSize: 12, fontWeight: 600, borderRadius: 6,
              background: 'rgba(255,255,255,0.04)', border: '1px solid rgba(255,255,255,0.1)',
              color: '#888', cursor: 'pointer', fontFamily: "'DM Sans', sans-serif",
            }}
          >
            Include All Systems
          </button>
        )}
        {includedCount > 0 && (
          <button
            onClick={copyResults}
            style={{
              flex: 1, padding: '8px 12px', fontSize: 12, fontWeight: 600, borderRadius: 6,
              background: copied ? 'rgba(72,199,142,0.12)' : 'rgba(233,69,96,0.08)',
              border: `1px solid ${copied ? 'rgba(72,199,142,0.3)' : 'rgba(233,69,96,0.2)'}`,
              color: copied ? '#48c78e' : '#e94560', cursor: 'pointer',
              fontFamily: "'DM Sans', sans-serif",
            }}
          >
            {copied ? 'Copied!' : 'Copy Results'}
          </button>
        )}
      </div>

      {/* Systems by Category */}
      <div style={{
        fontSize: 11, fontWeight: 700, color: '#e94560', letterSpacing: 1,
        marginBottom: 10, marginTop: 24,
      }}>
        BUILDING SYSTEMS ({includedCount} of {SYSTEMS.length} included)
      </div>

      {SYSTEM_CATEGORIES.map(cat => {
        const catSystems = SYSTEMS.filter(s => s.category === cat);
        const isExpanded = expandedCat === cat;
        const catIncluded = catSystems.filter(s => rows.find(r => r.system_key === s.key)?.included);

        return (
          <div key={cat} style={{ marginBottom: 8 }}>
            <button
              onClick={() => setExpandedCat(isExpanded ? null : cat)}
              style={{
                width: '100%', padding: '10px 12px', fontSize: 13, fontWeight: 600,
                background: 'rgba(255,255,255,0.03)', border: '1px solid rgba(255,255,255,0.08)',
                borderRadius: isExpanded ? '8px 8px 0 0' : 8, color: '#ccc', cursor: 'pointer',
                fontFamily: "'DM Sans', sans-serif", textAlign: 'left',
                display: 'flex', justifyContent: 'space-between', alignItems: 'center',
              }}
            >
              <span>{cat}</span>
              <span style={{ fontSize: 11, color: '#666' }}>
                {catIncluded.length}/{catSystems.length} {isExpanded ? '▾' : '▸'}
              </span>
            </button>

            {isExpanded && (
              <div style={{
                border: '1px solid rgba(255,255,255,0.08)', borderTop: 'none',
                borderRadius: '0 0 8px 8px', padding: '8px 0',
              }}>
                {catSystems.map(sys => {
                  const row = rows.find(r => r.system_key === sys.key);
                  if (!row) return null;
                  return (
                    <div key={sys.key} style={{
                      padding: '8px 12px',
                      background: row.included ? 'rgba(233,69,96,0.03)' : 'transparent',
                    }}>
                      {/* Toggle + Name */}
                      <div style={{
                        display: 'flex', alignItems: 'center', gap: 8, marginBottom: row.included ? 8 : 0,
                      }}>
                        <button
                          onClick={() => toggleSystem(sys.key)}
                          style={{
                            width: 20, height: 20, borderRadius: 4, flexShrink: 0,
                            border: `1px solid ${row.included ? '#e94560' : 'rgba(255,255,255,0.15)'}`,
                            background: row.included ? '#e94560' : 'transparent',
                            color: '#fff', fontSize: 12, cursor: 'pointer',
                            display: 'flex', alignItems: 'center', justifyContent: 'center',
                          }}
                        >
                          {row.included ? '✓' : ''}
                        </button>
                        <div style={{ flex: 1 }}>
                          <div style={{ fontSize: 13, fontWeight: 500, color: row.included ? '#eee' : '#888' }}>
                            {sys.name}
                          </div>
                          <div style={{ fontSize: 10, color: '#555' }}>
                            {formatCurrency(sys.cost)}/{sys.unitLabel} | {sys.usefulLife} yr life
                          </div>
                        </div>
                      </div>

                      {/* Detail inputs when included */}
                      {row.included && (
                        <div style={{
                          display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: 6,
                          paddingLeft: 28,
                        }}>
                          <div>
                            <label style={{ fontSize: 10, color: '#666', display: 'block', marginBottom: 2 }}>
                              Year Installed
                            </label>
                            <input
                              type="text"
                              inputMode="numeric"
                              value={row.year_installed}
                              onChange={e => updateRow(sys.key, 'year_installed', e.target.value)}
                              placeholder={String(yr - Math.round(sys.usefulLife / 2))}
                              maxLength={4}
                              style={{ ...inputBase, fontSize: 12, padding: '6px 8px' }}
                            />
                          </div>
                          <div>
                            <label style={{ fontSize: 10, color: '#666', display: 'block', marginBottom: 2 }}>
                              Condition
                            </label>
                            <select
                              value={row.condition}
                              onChange={e => updateRow(sys.key, 'condition', e.target.value)}
                              style={{ ...inputBase, fontSize: 12, padding: '6px 8px', appearance: 'auto' }}
                            >
                              {CONDITIONS.map(c => (
                                <option key={c} value={c}>{CONDITION_LABEL[c]}</option>
                              ))}
                            </select>
                          </div>
                          <div>
                            <label style={{ fontSize: 10, color: '#666', display: 'block', marginBottom: 2 }}>
                              {sys.unitLabel === 'lump sum' ? 'Multiplier' : `Qty (${sys.unitLabel})`}
                            </label>
                            <input
                              type="text"
                              inputMode="numeric"
                              value={row.quantity}
                              onChange={e => updateRow(sys.key, 'quantity', e.target.value)}
                              placeholder="0"
                              style={{ ...inputBase, fontSize: 12, padding: '6px 8px' }}
                            />
                          </div>
                        </div>
                      )}
                    </div>
                  );
                })}
              </div>
            )}
          </div>
        );
      })}

      {/* Top Urgent Systems */}
      {summary.topUrgent.length > 0 && (
        <div style={{ marginTop: 24 }}>
          <div style={{
            fontSize: 11, fontWeight: 700, color: '#e94560', letterSpacing: 1,
            marginBottom: 10,
          }}>
            TOP PRIORITY ITEMS
          </div>
          {summary.topUrgent.map((s, i) => (
            <div key={s.system_key} style={{
              display: 'flex', alignItems: 'center', gap: 10, padding: '8px 12px',
              background: i % 2 === 0 ? 'rgba(255,255,255,0.02)' : 'transparent',
              borderRadius: 6,
            }}>
              <div style={{
                width: 8, height: 8, borderRadius: 2, flexShrink: 0,
                background: URGENCY_COLORS[s.urgency] || '#666',
              }} />
              <div style={{ flex: 1, minWidth: 0 }}>
                <div style={{ fontSize: 13, fontWeight: 500 }}>{s.name}</div>
                <div style={{ fontSize: 10, color: '#666' }}>
                  {s.remainingLife === 0 ? 'Past useful life' : `${s.remainingLife} yrs remaining`}
                  {s.age != null && ` | ${s.age} yrs old`}
                </div>
              </div>
              <div style={{ fontSize: 13, fontWeight: 600, color: URGENCY_COLORS[s.urgency], flexShrink: 0 }}>
                {formatCurrency(s.replacementCost)}
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
